/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kai_com_weixingif_gifsicle_GifSicleRequest */

#ifndef _Included_kai_com_weixingif_gifsicle_GifSicleRequest
#define _Included_kai_com_weixingif_gifsicle_GifSicleRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kai_com_weixingif_gifsicle_GifSicleRequest
 * Method:    getGifInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kai_com_weixingif_gifsicle_GifSicleRequest_getGifInfo
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     kai_com_weixingif_gifsicle_GifSicleRequest
 * Method:    execute
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kai_com_weixingif_gifsicle_GifSicleRequest_execute
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
