/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_doutu_doutu_gifsicle_GifsicleUtil */

#ifndef _Included_xyz_doutu_doutu_gifsicle_GifsicleUtil
#define _Included_xyz_doutu_doutu_gifsicle_GifsicleUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_doutu_doutu_gifsicle_GifsicleUtil
 * Method:    execute
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_doutu_doutu_gifsicle_GifsicleUtil_execute
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
