/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_doutu_doutu_imagemagick_ImageMagickUtil */

#ifndef _Included_xyz_doutu_doutu_imagemagick_ImageMagickUtil
#define _Included_xyz_doutu_doutu_imagemagick_ImageMagickUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_doutu_doutu_imagemagick_ImageMagickUtil
 * Method:    convert
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xyz_doutu_doutu_imagemagick_ImageMagickUtil_convert
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
